import pandas as pd
from pathlib import Path

df = pd.read_csv("resources/input_files.csv", comment="#", index_col="arc_id")
all_arc_IDs = df.index
all_frame_names = df.frame_name


def get_tlm_filename(wildcards):
    return df.loc[wildcards.arc_id, "tlm_filename"]


def get_dat_filename(wildcards):
    return df.loc[wildcards.arc_id, "dat_filename"]


def get_arc_filename(wildcards):
    return df.loc[wildcards.arc_id, "arc_filename"]


rule all:
    input:
        flag_files=expand("results/flags/{arc_id}_added.flag", arc_id=all_arc_IDs),
        fitted_parameters=expand(
            "results/FittedParameters/{arc_id}_parameters.npy",
            arc_id=all_arc_IDs,
        ),
        # polynomial_values_file=expand(
        #     "results/PolynomialModelValues/{arc_id}_polynomial_coefficients.npy",
        #     arc_id=all_arc_IDs,
        # ),


rule make_database:
    output:
        database="results/database/arc_data.db",
    script:
        "scripts/create_db.py"


rule add_arc_frame:
    input:
        database=rules.make_database.output.database,
        dat_filename=get_dat_filename,
        tlm_filename=get_tlm_filename,
        arc_filename=get_arc_filename,
    output:
        flag_file="results/flags/{arc_id}_added.flag",
    script:
        "scripts/add_arc_frame.py"


rule fit_model:
    input:
        database=rules.make_database.output.database,
        flag_file=rules.add_arc_frame.output.flag_file,
    output:
        parameters="results/FittedParameters/{arc_id}_parameters.npy",
        plot_filename="results/Plots/{arc_id}_residuals.pdf",
    params:
        arc_id="{arc_id}",
    script:
        "scripts/linear_lst_sq.py"


# rule add_arc_frame:
#     input:
#         database="results/database/arc_data.db",
#         arc_frame="resources/ArcFrames/{arc_id}.fits",
#         tlm_frame=get_tlm_filename,
#         line_list="resources/LineLists/ccd3_CuAr_lines.csv",
#     output:
#         flag="results/flags/{arc_id}_added.flag",
#     script:
#         "scripts/fit_emission_lines.py"
# rule run_model:
#     input:
#         database="results/database/arc_data.db",
#         arc_fname="resources/ArcFrames/{arc_id}.fits",
#         stan_file="workflow/stan_models/hierarchical_model.stan",
#         flag="results/flags/{arc_id}_added.flag",
#     output:
#         plot="results/Plots/PolynomialModel/{arc_id}_coefficients.pdf",
#         polynomial_values_file="results/PolynomialModelValues/{arc_id}_polynomial_coefficients.npy",
#         fibre_numbers_file="results/PolynomialModelValues/{arc_id}_used_fibres.npy",
#     script:
#         "scripts/fit_hierarchical_model.py"
