site_name: Hector-Wave-Cal
site_description: Updated wavelength calibration for Hector
edit_uri: edit/main/docs

repo_url: https://github.com/Hector-Wave-Cal/
repo_name: Hector-Wave-Cal

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
